### PR TITLE
Delete Cormorant_OTF_Font_Family.zip

### PR DESCRIPTION
**Pull request by davelab6**
You can get a ZIP of the repo's current state from https://github.com/CatharsisFonts/Cormorant/archive/master.zip and if you want a zip of a particular commit, tag the commit as per the https://help.github.com/articles/creating-releases/ system

### CODE REVIEW

**Comment by CatharsisFonts** [comment]
Hi Dave, 

this particular ZIP file only contains the OTF exports and none of the sources, TTFs, and testing files. It it mean for people who just want to download and use the fonts. I feel that sending those users the full repo might just confuse them, since it is not immediately apparent what must be done to install the fonts, and they will have no use for all the other files.

**Comment by davelab6** [comment]
Sure. The release system allows you to attach this zip so users can
download it there and you can get a download count stat, and it doesn't
clutter the repo :)

**Comment by CatharsisFonts** [comment]
On 8/23/15 21:11 , Dave Crossland wrote:
> Sure. The release system allows you to attach this zip so users can
> download it there and you can get a download count stat, and it doesn't
> clutter the repo :)

I've been wondering why there's no download stat on the GitHub
page...  how does this work exactly?

BTW, does the current fix of the UPM and vertical metrics problem
work from your side?  Can we just run it through the bakery and
use it for GF, or do I still need to tweak things?

I feel like I'm not doing my downloaders a favor if the updated
version of the font is no longer metrically equivalent with the
one they might already have used.  I suppose I have to make this
change now, but I'd rather only make it once.  ;o)


-- 
Christian Thalmann
Swiss Federal Institute of Technology (ETH Zürich)
Institute for Astronomy
Wolfgang-Pauli-Strasse 27
CH-8093 Zürich
Switzerland

Phone: +41 (0)44 633 71 79

**Comment by CatharsisFonts** [comment]
On 8/23/15 21:11 , Dave Crossland wrote:
> and it doesn't
> clutter the repo :)

I do like the fact that I have a permalink to the most up-to-date
version of the installation package, though.  Is that also
possible with the releases?

-- 
Christian Thalmann
Swiss Federal Institute of Technology (ETH Zürich)
Institute for Astronomy
Wolfgang-Pauli-Strasse 27
CH-8093 Zürich
Switzerland

Phone: +41 (0)44 633 71 79

**Comment by davelab6** [comment]
On Aug 23, 2015 3:18 PM, "Christian Thalmann" <notifications@github.com>
wrote:
>
> On 8/23/15 21:11 , Dave Crossland wrote:
> > Sure. The release system allows you to attach this zip so users can
> > download it there and you can get a download count stat, and it doesn't
> > clutter the repo :)
>
> I've been wondering why there's no download stat on the GitHub
> page... how does this work exactly?

I don't think they are counting clone actions.

> BTW, does the current fix of the UPM and vertical metrics problem
> work from your side? Can we just run it through the bakery and
> use it for GF, or do I still need to tweak things?

I haven't checked anything since my post on the glyphs forum.

> I feel like I'm not doing my downloaders a favor if the updated
> version of the font is no longer metrically equivalent with the
> one they might already have used. I suppose I have to make this
> change now, but I'd rather only make it once. ;o)

Did you mark it 1.0 already?

**Comment by davelab6** [comment]
On Aug 23, 2015 3:20 PM, "Christian Thalmann" <notifications@github.com>
wrote:
>
> On 8/23/15 21:11 , Dave Crossland wrote:
> > and it doesn't
> > clutter the repo :)
>
> I do like the fact that I have a permalink to the most up-to-date
> version of the installation package, though. Is that also
> possible with the releases?

I don't think so. You could use an orphan branch

**Comment by CatharsisFonts** [comment]
>  > I feel like I'm not doing my downloaders a favor if the updated
>  > version of the font is no longer metrically equivalent with the
>  > one they might already have used. I suppose I have to make this
>  > change now, but I'd rather only make it once. ;o)
>
> Did you mark it 1.0 already?

Not yet.  I figured I'd start with something like 0.9 now and
switch to 1.0 when we ingest it at Google Fonts.  Does that work?

What's an orphan branch...?

If it's difficult to have a direct link to the newest download, I
guess I could just send people to the releases page and hope they
can navigate their way to the most recent download package...


Cheers,

-- 
Christian Thalmann
Swiss Federal Institute of Technology (ETH Zürich)
Institute for Astronomy
Wolfgang-Pauli-Strasse 27
CH-8093 Zürich
Switzerland

Phone: +41 (0)44 633 71 79

**Comment by khaledhosny** [comment]
> I do like the fact that I have a permalink to the most up-to-date version 

You can use a link like https://github.com/khaledhosny/amiri-font/releases/latest

**Comment by davelab6** [comment]
On 23 August 2015 at 15:46, Khaled Hosny <notifications@github.com> wrote:

> I do like the fact that I have a permalink to the most up-to-date version
>
> You can use a link like
> https://github.com/khaledhosny/amiri-font/releases/latest
>

Perfect!

**Comment by CatharsisFonts** [comment]
Yes, that link works perfectly!

For the releases, I figure it might be preferable to have only
one type of font files (TTF?) and a human-readable README file
(the .md looks bad in a text editor) as a "simple installation"
archive.  A full installation could then also be offered
including the whole repo.  Does that make sense?

-- 
Christian Thalmann
Swiss Federal Institute of Technology (ETH Zürich)
Institute for Astronomy
Wolfgang-Pauli-Strasse 27
CH-8093 Zürich
Switzerland

Phone: +41 (0)44 633 71 79

**Comment by davelab6** [comment]
> For the releases, I figure it might be preferable to have only
> one type of font files (TTF?) and a human-readable README file
> (the .md looks bad in a text editor)

MD should look good in a text editor.

> as a "simple installation"
> archive.  A full installation could then also be offered
> including the whole repo.  Does that make sense?

I think you have this set up well now

**Pull request closed without merging**
