### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by davelab6**
Use reference-style links to make the file more friendly for reading as plain text

### CODE REVIEW

**Comment by CatharsisFonts** [comment]
Thanks, I adopted your version of the README, it's much better.

I also reorganized the folders of the repo a bit, since they're
going to be used as the default installation package now.

BTW, can I rename README.md to "0. README.md", or will it no
longer work on GitHub?

-- 
Christian Thalmann
Swiss Federal Institute of Technology (ETH Zürich)
Institute for Astronomy
Wolfgang-Pauli-Strasse 27
CH-8093 Zürich
Switzerland

Phone: +41 (0)44 633 71 79

**Comment by CatharsisFonts** [comment]
The whole repo yields a 153 MB ZIP file, though...  I guess it
would still be better to offer a dedicated "simple install" ZIP
file without the sources.  I might as well make a plain text
readme for that purpose...

On 8/23/15 23:15 , Dave Crossland wrote:
> Use reference-style links to make the file more friendly for reading as
> plain text
>

-- 
Christian Thalmann
Swiss Federal Institute of Technology (ETH Zürich)
Institute for Astronomy
Wolfgang-Pauli-Strasse 27
CH-8093 Zürich
Switzerland

Phone: +41 (0)44 633 71 79

**Comment by CatharsisFonts** [comment]
On 8/23/15 23:45 , Christian Thalmann wrote:
> The whole repo yields a 153 MB ZIP file, though...  I guess it
> would still be better to offer a dedicated "simple install" ZIP
> file without the sources.  I might as well make a plain text
> readme for that purpose...

Actually, never mind, most of that huge file size is due to
the invisible GitHub stuff in the directory.  If I just export
the actual content of the directory including sources, it
shouldn't be much larger than the OTFs alone.

-- 
Christian Thalmann
Swiss Federal Institute of Technology (ETH Zürich)
Institute for Astronomy
Wolfgang-Pauli-Strasse 27
CH-8093 Zürich
Switzerland

Phone: +41 (0)44 633 71 79

**Comment by davelab6** [comment]
> Thanks, I adopted your version of the README, it's much better.

However, you didn't merge this pull request to do so; next time, I suggest that :)

> BTW, can I rename README.md to "0. README.md", or will it no
> longer work on GitHub?

No, it must be README.md for it to appear on https://github.com/CatharsisFonts/Cormorant/

> The whole repo yields a 153 MB ZIP file

It got so huge because you put a big binary file in it, and every version of that file is kept, whereas with the text files, only the differences are kept, keeping the repo size much smaller.

**Comment by CatharsisFonts** [comment]
On 8/24/15 1:06 , Dave Crossland wrote:

> However, you didn't merge this pull request to do so; next time, I
> suggest that :)

I had already played around with the directory structure at that
point and was worried that your branch would no longer match mine
well.  ;o)


>     The whole repo yields a 153 MB ZIP file
>
> It got so huge because you put a big binary file in it, and every
> version of that file is kept, whereas with the text files, only the
> differences are kept, keeping the repo size much smaller.

Argh...  any way to purge the old versions on the local repo?


-- 
Christian Thalmann
Swiss Federal Institute of Technology (ETH Zürich)
Institute for Astronomy
Wolfgang-Pauli-Strasse 27
CH-8093 Zürich
Switzerland

Phone: +41 (0)44 633 71 79

**Comment by davelab6** [comment]
> any way to purge the old versions on the local repo?

Try the BFG as in https://help.github.com/articles/remove-sensitive-data/

**Comment by CatharsisFonts** [comment]
On 8/24/15 1:26 , Dave Crossland wrote:
>     any way to purge the old versions on the local repo?
>
> Try the BFG as in https://help.github.com/articles/remove-sensitive-data/

I've run it, and it deleted 500+ files, most of them being font
files rather than the ZIP file.  Sounds scary!  But I did make a
local backup of the "bare" clone.  So should I go through with the
rest of the BFG procedure...?

-- 
Christian Thalmann
Swiss Federal Institute of Technology (ETH Zürich)
Institute for Astronomy
Wolfgang-Pauli-Strasse 27
CH-8093 Zürich
Switzerland

Phone: +41 (0)44 633 71 79

**Comment by CatharsisFonts** [comment]
On 8/24/15 1:57 , Christian Thalmann wrote:
>
>
> On 8/24/15 1:26 , Dave Crossland wrote:
>>     any way to purge the old versions on the local repo?
>>
>> Try the BFG as in https://help.github.com/articles/remove-sensitive-data/
>
> I've run it, and it deleted 500+ files, most of them being font
> files rather than the ZIP file.  Sounds scary!  But I did make a
> local backup of the "bare" clone.  So should I go through with the
> rest of the BFG procedure...?

Meh, I don't know enough about what I'm doing.  I don't feel like
accidentally deleting everything.  :P  The installer package is now
light-weight after all, I guess there's not much hurt in the repo
itself being 150 MB (or is there?).  I've left it untouched for now.
Time for bed.

-- 
Christian Thalmann
Swiss Federal Institute of Technology (ETH Zürich)
Institute for Astronomy
Wolfgang-Pauli-Strasse 27
CH-8093 Zürich
Switzerland

Phone: +41 (0)44 633 71 79

**Pull request closed without merging**
