### PR TITLE
v3.301 Mastered for Google Fonts

### PR DESCRIPTION
**Pull request by m4rc1e**
Hey,

I've mastered your fonts so they comply with our [spec](https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist.md). Due to the amount of files and your repo structure being quite good, I've left it alone. 

All fonts have been regenerated. 

Thank you for your hard work sir.

### CODE REVIEW

**Comment by CatharsisFonts** [comment]
Thanks! 😁 

What does the mastering entail, exactly? There seems to be a large volume of changes to the source files.

**Comment by m4rc1e** [comment]
- Version number increase.
- Revised Copyright notice
- Null and NB space glyphs added
- Manufacturer and Manufacturer Url included
- There was an issue with the 'Increase upm'=1000 customParameter. I found it was creating errors/collisions with accent marks. This probably dented the files the most. I'll send a screenshot of this tomorrow.

**Comment by CatharsisFonts** [comment]
Oof, you rescaled the masters to 1000 UPM? I think I intentionally avoided that so as not to mess up the paths at the micro level. Some of the strokes are only 10 units thick and have short handles... \

At first sight, they still look OK, though. I hope I don't have to go over them with a fine-toothed comb.

I trust the metrics should still be the same as before?

**Comment by m4rc1e** [comment]
Well you had the customParameter 'Scale to upm' set to 1000 for each instance. This will have exactly the same effect.

**Comment by CatharsisFonts** [comment]
I seem to remember that the custom parameter is applied on the floating-point coordinates of the interpolated instances, and is therefore more accurate. But I guess it will still be rounded again afterwards, which might erase that percision again.

**Comment by m4rc1e** [comment]
Alright,

If you find any issues with my approach feel free to revert. However, I want you at the very least to implement the current font data 

screen shot 2017-01-11 at 21 27 40

The vertical metrics were also changed. However, the new values retain the same line spacing as the previous release

screen shot 2017-01-11 at 21 28 46


screen shot 2017-01-11 at 16 40 53

Also run this [script](https://github.com/m4rc1e/mf-glyphs-scripts/blob/master/Fixes/fix_gf_spec.py)

I don't have the time to generate off all 220+ fonts each time. I wasted the whole day on this project and am replying to this at 9:30.

**Comment by CatharsisFonts** [comment]
Nah, it's fine. I haven't seen any indication of path deterioration in your version. I'm glad to see that not only is the line spacing the same, but also the glyphs appear as large as before.

> I wasted the whole day on this project and am replying to this at 9:30pm.
I wouldn't call it a waste. 😉 And it's 22:44 over here, in case it matters.

**Comment by m4rc1e** [comment]
:-) 

I woke up this morning thinking this would be 2 hours max lol.

Night mate

**Comment by CatharsisFonts** [comment]
Argh, I just noticed my new /R.ss02 is not being exported into the Garamond cuts. I guess I didn't run the script that refreshes the custom parameters that produce the spin-off instances.

I assume I'm not breaking any of your work if I run those scripts and re-export the fonts in the current live version?

**Comment by m4rc1e** [comment]
That's fine. It won't break any of my changes.

Just regen and let me know when you're happy. 

Cheers,
Marc

**Comment by m4rc1e** [comment]
@CatharsisFonts just out of curiosity. How long has this taken you?

This is looks like tonnes of work.

I am a fan.

**Comment by CatharsisFonts** [comment]
Great, will do.

As for the work time, I have no idea in terms of hours, as it was mostly done in irregular chunks of leisure time. This thread documents some of the progress history, though:

http://typedrawers.com/discussion/791/paramond-an-extreme-display-serif/p1

Cheers!

**Pull request merged**
