### PR TITLE
v4.000 mastered for Google Fonts

### PR DESCRIPTION
**Pull request by m4rc1e**
Hey,

Long time no see. Hope you're doing well. We decided that we'll help out so we can finally push an update to Google Fonts. A lot of our processes have changed since we last pushed this family. I'll highlight some of the key changes.

**Repo reorganisation**

The structure now closely resembles our standardised project template, https://github.com/googlefonts/googlefonts-project-template. I've also removed the old ufo sources since these are the not the source of truth (the glyphs files are).

**Variable fonts**

A single VF family has been included. The variable font is generated using our [gftools builder](https://github.com/googlefonts/gftools). We want to move away from generating fonts using Glyphsapp because we cannot guarantee that future versions of this software will generate identical fonts. By using our own tool chain, we can pin the dependencies so we get repeatable builds.

**Build instructions**

Added instructions on how to build the variable fonts, static fonts and webfonts.

**Deprecated eot and woff webfonts**

We now only provide woff2 because browser support has improved. .eot are also only usable on Internet Explorer which is pretty much dead.

**Further notes**

Our future plan is to eventually drop the SC, Garamond, Infant families etc once the Google Fonts api fully supports OpenType features. This means we won't need to use Glyhpsapp to generating these sibling families since they are redundant.

### CODE REVIEW

**Comment by m4rc1e** [comment]
Here's the changes that are going to get merged in, https://github.com/m4rc1e/Cormorant/tree/gf-mastering

**Comment by CatharsisFonts** [comment]
Hi @m4rc1e!

Sounds good overall; thanks for your work.

I'm not too happy about the loss of the Garamond and Infant cuts. I suspect either of them are more valuable to the user (the Garamond one certainly used to be the most popular one by a large margin, back when usage stats were displayed on GF), and most users are going to miss out on even the existence of these options if they come hidden in a bunch of stylistic alternate features.

Looking at the «diff» page, I see some lines getting shorter or longer when I switch between Before and After. I believe the behavior is driven by a few punctuation marks. Did you correct some sidebearings or remove some kerning, or is that an unintentional side effect?

Cheers, Christian

**Comment by m4rc1e** [comment]
> I'm not too happy about the loss of the Garamond and Infant cuts. I suspect either of them are more valuable to the user (the Garamond one certainly used to be the most popular one by a large margin, back when usage stats were displayed on GF), and most users are going to miss out on even the existence of these options if they come hidden in a bunch of stylistic alternate features.

That's fair enough. Cormorant Garamond is actually the most popular out of all the families so you do raise a good point. However, in order for us to make variable fonts of the sibling families using our current tooling is impossible. It will also take us quite a while in order to support this. Do you mind if we release Cormorant as a variable font and the other families as static fonts for the time being?

> Looking at the «diff» page, I see some lines getting shorter or longer when I switch between Before and After. I believe the behavior is driven by a few punctuation marks. Did you correct some sidebearings or remove some kerning, or is that an unintentional side effect?

Seems to be an unintentional side effect. I did open the fonts in Glyphs3 in order to change some metadata but I never touched the design work. It could either be Glyphs3 or fontmake. Are the changes a deal breaker? if so I'll take a look and see what's causing it.

**Comment by CatharsisFonts** [comment]
> Do you mind if we release Cormorant as a variable font and the other families as static fonts for the time being?
That's perfectly fine by me.

> Are the changes a deal breaker? if so I'll take a look and see what's causing it.
I'm unhappy with random changes to my glyphs, yes, even if it's not going to come up... there might be worse digressions that I haven't even seen yet. 

In any case, isn't the entire point of your pipeline to ensure a transparent export without regressions? Wouldn't you want to hunt down that bug anyway?

Cheers, Christian

**Comment by CatharsisFonts** [comment]
Actually, it seems that /quoteright/ not only changes width but also gains some weight around its waist. Looking at my source file, it seems that my comma (which is used in /quoteright/) used to be lighter in the past and was replaced by a heftier version a while back (March 2017). Could it be that your «Before» version is not from the current GitHub commit but from the last GF upload...?

Cheers, Christian

**Comment by CatharsisFonts** [comment]
Hi @m4rc1e ,

OK, I replaced Cormorant Light in the «fonts_before» folder with my own current version, and that removes the differences. Apparently you were using an obsolete version of Cormorant for comparison. 

I'm fine with the changes, then.

Cheers, Christian

**Comment by CatharsisFonts** [comment]
OK, now Git won't let me pull the merged version because of some conflicts. How do I ask Git to overwrite my local version with the remote one?

**Comment by m4rc1e** [comment]
How about the following (copy and paste each line

```
get checkout master # takes us to master branch
git reset --hard f4da9c651c2aabdbf470953b76ed43281fc24f69 # takes us back to commit f4da9c651c2aabdbf470953b76ed43281fc24f69 which is the one before i did my work
git pull origin master # pulls in the latest stuff
```

If you're stuck in the middle of a rebase, you may want to do `git rebase --abort` or `git merge --abort` which should cancel the failed merge

**Comment by CatharsisFonts** [comment]
Hi @m4rc1e,

I was able to abort the merge and execute your lines. Git seems happy now, but my local directories are still set up the old way («1. TrueType Font Files» instead of «sources»), so I think something's still wrong. I don't get any new changes by executing «git pull origin master» though.

Cheers, Christian

**Pull request merged**
